CREATE DATABASE qa;

\c qa;

CREATE TABLE IF NOT EXISTS questions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer,
  body text,
  date_written bigint,
  asker_name varchar(255),
  asker_email varchar(255),
  reported integer,
  helpful integer
);

CREATE TABLE IF NOT EXISTS answers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id integer,
  body text,
  date_written bigint,
  answerer_name varchar(255),
  answerer_email varchar(255),
  reported integer,
  helpful integer,
  CONSTRAINT fk_questions
    FOREIGN KEY (question_id)
    REFERENCES questions(id)
);

CREATE TABLE IF NOT EXISTS answers_photos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_id integer,
  url text,
  CONSTRAINT fk_answers
    FOREIGN KEY (answer_id)
    REFERENCES answers(id)
);